### PR TITLE
fix: ensure options is always an array

### LINKED ISSUE #4009: Master: json_decode(): Argument #1 ($json) must be of type string, null given"
On our Daily:
```
{
  "reqId": "IT0uA95B4JD9ERvtadsC",
  "level": 3,
  "time": "2025-09-23T04:55:52+00:00",
  "remoteAddr": "2a02:8071:64e0:7bc0:3ef3:d17f:210f:4af7",
  "user": "admin",
  "app": "index",
  "method": "GET",
  "url": "/apps/dashboard/",
  "message": "json_decode(): Argument #1 ($json) must be of type string, null given",
  "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:143.0) Gecko/20100101 Firefox/143.0",
  "version": "33.0.0.0",
  "exception": {
    "Exception": "TypeError",
    "Message": "json_decode(): Argument #1 ($json) must be of type string, null given",
    "Code": 0,
    "Trace": [
      {
        "file": "/var/www/html/apps/groupfolders/lib/Folder/FolderManager.php",
        "line": 553,
        "function": "json_decode",
        "args": [
          null,
          true
        ]
      },
      {
        "file": "/var/www/html/apps/groupfolders/lib/Folder/FolderManager.php",
        "line": 597,
        "function": "rowToFolder",
        "class": "OCA\\GroupFolders\\Folder\\FolderManager",
        "type": "->",
        "args": [
          "*** sensitive parameters replaced ***"
        ]
      },
      {
        "function": "OCA\\GroupFolders\\Folder\\{closure}",
        "class": "OCA\\GroupFolders\\Folder\\FolderManager",
        "type": "->",
        "args": [
          "*** sensitive parameters replaced ***"
        ]
      },
      {
        "file": "/var/www/html/apps/groupfolders/lib/Folder/FolderManager.php",
        "line": 596,
        "function": "array_map",
        "args": [
          {
            "__class__": "Closure"
          },
          [
            "*** sensitive parameters replaced ***",
            {
              "folder_id": 3,
              "mount_point": "Design review team folder",
              "quota": -4,
              "acl": 1,
              "storage_id": 2,
              "0": "And 16 more entries, set log level to debug to see all entries"
            }
          ]
        ]
      },
      {
        "file": "/var/www/html/apps/groupfolders/lib/Folder/FolderManager.php",
        "line": 894,
        "function": "getFoldersForGroups",
        "class": "OCA\\GroupFolders\\Folder\\FolderManager",
        "type": "->",
        "args": [
          [
            "admin"
          ],
          null
        ]
      },
      {
        "file": "/var/www/html/apps/groupfolders/lib/AppInfo/Capabilities.php",
        "line": 47,
        "function": "getFoldersForUser",
        "class": "OCA\\GroupFolders\\Folder\\FolderManager",
        "type": "->",
        "args": [
          {
            "__class__": "OC\\User\\User"
          }
        ]
      },
      {
        "file": "/var/www/html/apps/groupfolders/lib/AppInfo/Capabilities.php",
        "line": 41,
        "function": "hasFolders",
        "class": "OCA\\GroupFolders\\AppInfo\\Capabilities",
        "type": "->",
        "args": [
          {
            "__class__": "OC\\User\\User"
          }
        ]
      },
      {
        "file": "/var/www/html/lib/private/CapabilitiesManager.php",
        "line": 61,
        "function": "getCapabilities",
        "class": "OCA\\GroupFolders\\AppInfo\\Capabilities",
        "type": "->",
        "args": []
      },
      {
        "file": "/var/www/html/lib/private/Template/JSConfigHelper.php",
        "line": 142,
        "function": "getCapabilities",
        "class": "OC\\CapabilitiesManager",
        "type": "->",
        "args": [
          false,
          true
        ]
      },
      {
        "file": "/var/www/html/lib/private/TemplateLayout.php",
        "line": 237,
        "function": "getConfig",
        "class": "OC\\Template\\JSConfigHelper",
        "type": "->",
        "args": []
      },
      {
        "file": "/var/www/html/lib/private/Template/Template.php",
        "line": 115,
        "function": "getPageTemplate",
        "class": "OC\\TemplateLayout",
        "type": "->",
        "args": [
          "user",
          "dashboard"
        ]
      },
      {
        "file": "/var/www/html/lib/public/AppFramework/Http/TemplateResponse.php",
        "line": 195,
        "function": "fetchPage",
        "class": "OC\\Template\\Template",
        "type": "->",
        "args": [
          {
            "id-app-content": "#app-dashboard",
            "id-app-navigation": null,
            "pageTitle": "Dashboard"
          }
        ]
      },
      {
        "file": "/var/www/html/lib/private/AppFramework/Http/Dispatcher.php",
        "line": 163,
        "function": "render",
        "class": "OCP\\AppFramework\\Http\\TemplateResponse",
        "type": "->",
        "args": []
      },
      {
        "file": "/var/www/html/lib/private/AppFramework/App.php",
        "line": 153,
        "function": "dispatch",
        "class": "OC\\AppFramework\\Http\\Dispatcher",
        "type": "->",
        "args": [
          {
            "__class__": "OCA\\Dashboard\\Controller\\DashboardController"
          },
          "index"
        ]
      },
      {
        "file": "/var/www/html/lib/private/Route/Router.php",
        "line": 321,
        "function": "main",
        "class": "OC\\AppFramework\\App",
        "type": "::",
        "args": [
          "OCA\\Dashboard\\Controller\\DashboardController",
          "index",
          {
            "__class__": "OC\\AppFramework\\DependencyInjection\\DIContainer"
          },
          {
            "_route": "dashboard.dashboard.index"
          }
        ]
      },
      {
        "file": "/var/www/html/lib/base.php",
        "line": 1061,
        "function": "match",
        "class": "OC\\Route\\Router",
        "type": "->",
        "args": [
          "/apps/dashboard/"
        ]
      },
      {
        "file": "/var/www/html/index.php",
        "line": 25,
        "function": "handleRequest",
        "class": "OC",
        "type": "::",
        "args": []
      }
    ],
    "File": "/var/www/html/apps/groupfolders/lib/Folder/FolderManager.php",
    "Line": 553,
    "message": "json_decode(): Argument #1 ($json) must be of type string, null given",
    "exception": {},
    "CustomMessage": "json_decode(): Argument #1 ($json) must be of type string, null given"
  }
}

```

I thus needed to disable the app.

### PR DESCRIPTION
**Pull request by kesselb**
Fix #4009

### CODE REVIEW

File: lib/Folder/FolderManager.php [hunk 1]
```diff
@@ -549,16 +549,33 @@ public function searchUsers(int $id, string $search = '', int $limit = 10, int $
...
+			$options = json_decode($row['options'], true, 512, JSON_THROW_ON_ERROR);
+		} catch (\JsonException $e) {
+			return [];
+		}
+
+		if (!is_array($options)) {
+			return [];
+		}
+
+		return $options;
```
Comment (solracsf) [inline lib/Folder/FolderManager.php:568]: `return is_array($options) ? $options : [];`

🙈

File: lib/Folder/FolderManager.php [hunk 2]
```diff
@@ -549,16 +549,33 @@ public function searchUsers(int $id, string $search = '', int $limit = 10, int $
...
+	private function getFolderOptions(array $row): array {
+		if (!isset($row['options'])) {
+			return [];
+		}
+
+		try {
+			$options = json_decode($row['options'], true, 512, JSON_THROW_ON_ERROR);
+		} catch (\JsonException $e) {
+			return [];
+		}
```
Comment (come-nc) [inline lib/Folder/FolderManager.php:562]: The error should be logged.

**Review by come-nc — CHANGES_REQUESTED** [review]

File: lib/Folder/FolderManager.php (hunk 2 above)
Comment (kesselb) [reply lib/Folder/FolderManager.php:562]: Done

**Review by provokateurin — APPROVED** [review]

**Comment by come-nc** [comment]
(31 does not have the method so does not need the fix I think)

**Comment by ollimaz** [comment]
> (31 does not have the method so does not need the fix I think)

I disagree I've got the same issues after updating to 19.1.7

**Comment by MichaIng** [comment]
> I disagree I've got the same issues after updating to 19.1.7

Please compare the error messages carefully. This PR fixes
```
TypeError: json_decode(): Argument #1 ($json) must be of type string, null given in PATH/apps/groupfolders/lib/Folder/FolderManager.php
```
as reported here: #4037

This cannot appear on app versions below 20, i.e. not on Nextcloud 31 or lower.
