### PR TITLE
Fix expire commands and background job when trash and/or version apps are disabled

### LINKED ISSUE #1812: Error: Interface 'OCA\Files_Versions\Versions\IVersionBackend' not found
Just upgraded NC from 22.2.3 to 23.0.0.10 with groupfolders 11.1.0 and now get constant errors after upgrade:

NC log
```
Fatal	no app in context	Error: Interface 'OCA\Files_Versions\Versions\IVersionBackend' not found

occ error message
An unhandled exception has been thrown:
Error: Interface 'OCA\Files_Versions\Versions\IVersionBackend' not found in XXXXX/apps/groupfolders/lib/Versions/VersionsBackend.php:38
```

I see a fix back in 2019 for a similar error message:
https://github.com/nextcloud/groupfolders/commit/fa87c7164d01fa4732fcbbc4b498cb4b2926b42e

### LINKED ISSUE #1815: Scanning filesystem crash when "Deleted files" app is disabled
Using latest available nextcloud (23.0.0) and groupfolders (11.1.0).

I run `occ groupfolders:scan 1`

When trashbin (a.k.a Deleted files app) it seems to work.
When trashbin is disabled I get this error:

```
Error: Interface "OCA\Files_Trashbin\Trash\ITrashBackend" not found in /var/www/mysite/apps/groupfolders/lib/Trash/TrashBackend.php:43
Stack trace:
#0 /var/www/mysite/lib/composer/composer/ClassLoader.php(571): include()
#1 /var/www/mysite/lib/composer/composer/ClassLoader.php(428): Composer\Autoload\includeFile('/var/www/mysite....')
#2 /var/www/mysite/apps/groupfolders/lib/AppInfo/Application.php(87): Composer\Autoload\ClassLoader->loadClass('OCA\\GroupFolder...')
#3 /var/www/mysite/lib/private/AppFramework/Utility/SimpleContainer.php(160): OCA\GroupFolders\AppInfo\Application->OCA\GroupFolders\AppInfo\{closure}(Object(OC\AppFramework\DependencyInjection\DIContainer))
#4 /var/www/mysite/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(Pimple\Container))
#5 /var/www/mysite/lib/private/AppFramework/Utility/SimpleContainer.php(127): Pimple\Container->offsetGet('OCA\\GroupFolder...')
#6 /var/www/mysite/lib/private/AppFramework/DependencyInjection/DIContainer.php(457): OC\AppFramework\Utility\SimpleContainer->query('OCA\\GroupFolder...')
#7 /var/www/mysite/lib/private/AppFramework/DependencyInjection/DIContainer.php(435): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback('OCA\\GroupFolder...')
#8 /var/www/mysite/lib/private/AppFramework/Utility/SimpleContainer.php(56): OC\AppFramework\DependencyInjection\DIContainer->query('OCA\\GroupFolder...')
#9 /var/www/mysite/apps/groupfolders/lib/AppInfo/Application.php(110): OC\AppFramework\Utility\SimpleContainer->get('OCA\\GroupFolder...')
#10 /var/www/mysite/lib/private/AppFramework/Utility/SimpleContainer.php(160): OCA\GroupFolders\AppInfo\Application->OCA\GroupFolders\AppInfo\{closure}(Object(OC\AppFramework\DependencyInjection\DIContainer))
#11 /var/www/mysite/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(Pimple\Container))
#12 /var/www/mysite/lib/private/AppFramework/Utility/SimpleContainer.php(127): Pimple\Container->offsetGet('OCA\\GroupFolder...')
#13 /var/www/mysite/lib/private/AppFramework/DependencyInjection/DIContainer.php(457): OC\AppFramework\Utility\SimpleContainer->query('OCA\\GroupFolder...')
#14 /var/www/mysite/lib/private/ServerContainer.php(145): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback('OCA\\GroupFolder...')
#15 /var/www/mysite/lib/private/Console/Application.php(217): OC\ServerContainer->query('OCA\\GroupFolder...')
#16 /var/www/mysite/lib/private/Console/Application.php(128): OC\Console\Application->loadCommandsFromInfoXml(Array)
#17 /var/www/mysite/console.php(98): OC\Console\Application->loadCommands(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /var/www/mysite/occ(11): require_once('/var/www/mysite....')
```

### PR DESCRIPTION
**Pull request by CarlSchwan**
Fix #1815

Fix #1812

For the background jobs, split the version expiration and trash expiration in two separate jobs. Both use the same placeholder in case the respective app is not enabled.

For the commands, create 4 different versions (using inheritance) with the 4 different combo enabled/disabled.

Signed-off-by: Carl Schwan <carl@carlschwan.eu>

### CODE REVIEW

**Review by fschrempf — APPROVED** [review]
Overall this looks good to me, but I'm not familiar enough with the codebase to provide a thorough review at the moment.

File: lib/BackgroundJob/ExpireGroupPlaceholder.php [hunk 1]
```diff
@@ -1,6 +1,7 @@
 <?php declare(strict_types=1);
 /**
  * @copyright Copyright (c) 2018 Robin Appelman <robin@icewind.nl>
+ * @copyright Copyright (c) 2021 Carl Schwan <carl@carlschwan.eu>
```
Comment (Pytal) [inline lib/BackgroundJob/ExpireGroupPlaceholder.php:4]:
```suggestion
 * @copyright Copyright (c) 2022 Carl Schwan <carl@carlschwan.eu>
```

**Review by come-nc — APPROVED** [review]
Make sure you test before merge.

**Comment by CarlSchwan** [comment]
Tested with the 4 combinations and everything work!
