### PR TITLE
Fix migration issue

### LINKED ISSUE #4018: Enabling Groupfolders 20.0.1 on Nextcloud 32.0.0 RC4 (32.0.0.12) - OCP\\Util::numericToNumber(): Argument #1 ($number) must be of type string|int|float, null given
Hi,

Builded a Nextcloud 32.0.0 RC4 container, with latest app release of Groupfolders v20.0.1.
However, when I enabled this app, it results into a Internal Server Error, with in the logs;

```
{"reqId":"YrjoduqPTAfCKGrH5gv2","level":3,"time":"26/Sep/2025:10:50:29","remoteAddr":"10.11.0.25","user":"johndoe","app":"index","method":"GET","url":"/settings/admin/overview","message":"OCP\\Util::numericToNumber(): Argument #1 ($number) must be of type string|int|float, null given, called in /var/www/nextcloud/lib/private/Files/Cache/Cache.php on line 162","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:143.0) Gecko/20100101 Firefox/143.0","version":"32.0.0.12","exception":{"Exception":"TypeError","Message":"OCP\\Util::numericToNumber(): Argument #1 ($number) must be of type string|int|float, null given, called in /var/www/nextcloud/lib/private/Files/Cache/Cache.php on line 162","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/Files/Cache/Cache.php","line":162,"function":"numericToNumber","class":"OCP\\Util","type":"::","args":[null]},{"file":"/var/www/nextcloud/custom_apps/groupfolders/lib/Folder/FolderManager.php","line":646,"function":"cacheEntryFromData","class":"OC\\Files\\Cache\\Cache","type":"::","args":["*** sensitive parameters replaced ***",{"__class__":"OC\\Files\\Type\\Loader"}]},{"function":"OCA\\GroupFolders\\Folder\\{closure}","class":"OCA\\GroupFolders\\Folder\\FolderManager","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/custom_apps/groupfolders/lib/Folder/FolderManager.php","line":642,"function":"array_map","args":[{"__class__":"Closure"},["*** sensitive parameters replaced ***","*** sensitive parameters replaced ***"]]},{"file":"/var/www/nextcloud/custom_apps/groupfolders/lib/Folder/FolderManager.php","line":889,"function":"getFoldersFromCircleMemberships","class":"OCA\\GroupFolders\\Folder\\FolderManager","type":"->","args":[{"__class__":"OC\\User\\User"},null]},{"file":"/var/www/nextcloud/custom_apps/groupfolders/lib/AppInfo/Capabilities.php","line":47,"function":"getFoldersForUser","class":"OCA\\GroupFolders\\Folder\\FolderManager","type":"->","args":[{"__class__":"OC\\User\\User"}]},{"file":"/var/www/nextcloud/custom_apps/groupfolders/lib/AppInfo/Capabilities.php","line":41,"function":"hasFolders","class":"OCA\\GroupFolders\\AppInfo\\Capabilities","type":"->","args":[{"__class__":"OC\\User\\User"}]},{"file":"/var/www/nextcloud/lib/private/CapabilitiesManager.php","line":61,"function":"getCapabilities","class":"OCA\\GroupFolders\\AppInfo\\Capabilities","type":"->","args":[]},{"file":"/var/www/nextcloud/lib/private/Template/JSConfigHelper.php","line":142,"function":"getCapabilities","class":"OC\\CapabilitiesManager","type":"->","args":[false,true]},{"file":"/var/www/nextcloud/lib/private/TemplateLayout.php","line":237,"function":"getConfig","class":"OC\\Template\\JSConfigHelper","type":"->","args":[]},{"file":"/var/www/nextcloud/lib/private/Template/Template.php","line":115,"function":"getPageTemplate","class":"OC\\TemplateLayout","type":"->","args":["user","settings"]},{"file":"/var/www/nextcloud/lib/public/AppFramework/Http/TemplateResponse.php","line":195,"function":"fetchPage","class":"OC\\Template\\Template","type":"->","args":[{"content":"\n<div id=\"vue-admin-settings-setup-checks\"></div>\n\n<div id=\"version\" class=\"section\">\n\t<!-- should be the last part, so Updater can follow if enabled (it has no heading therefore). -->\n\t<h2>Version</h2>\n\t<p><strong><a href=\"https://example.com\" rel=\"noreferrer noopener\" target=\"_blank\">Nextcloud Hub 25 Autumn</a> (32.0.0 RC4)</strong></p>\n</div>\n\n<div id=\"updatenotification\"></div>\n","forms":{"personal":[{"anchor":"personal-info","section-name":"Personal info","active":false,"icon":"/core/img/actions/user.svg"},{"anchor":"security","section-name":"Security","active":false,"icon":"/apps/settings/img/password.svg"},{"anchor":"notifications","section-name":"Notifications","active":false,"icon":"/apps/notifications/img/notifications-dark.svg"},{"anchor":"externalstorages","section-name":"External storage","active":false,"icon":"/apps/files_external/img/app-dark.svg"},{"anchor":"sync-clients","section-name":"Mobile & desktop","active":false,"icon":"/core/img/clients/phone.svg"},"And 4 more entries, set log level to debug to see all entries"],"admin":[{"anchor":"overview","section-name":"Overview","active":true,"icon":"/apps/settings/img/admin.svg"},{"anchor":"presets","section-name":"Quick presets","active":false,"icon":"/apps/settings/img/library_add_check.svg"},{"anchor":"support","section-name":"Support","active":false,"icon":"/apps/support/img/section.svg"},{"anchor":"server","section-name":"Basic settings","active":false,"icon":"/core/img/actions/settings-dark.svg"},{"anchor":"sharing","section-name":"Sharing","active":false,"icon":"/core/img/actions/share.svg"},"And 16 more entries, set log level to debug to see all entries"]},"pageTitle":"Overview","activeSectionId":"overview","activeSectionType":"admin"}]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":163,"function":"render","class":"OCP\\AppFramework\\Http\\TemplateResponse","type":"->","args":[]},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":153,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Settings\\Controller\\AdminSettingsController"},"index"]},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":321,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Settings\\Controller\\AdminSettingsController","index",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"settings.adminsettings.index","section":"overview"}]},{"file":"/var/www/nextcloud/lib/base.php","line":1061,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/settings/admin/overview"]},{"file":"/var/www/nextcloud/index.php","line":25,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/nextcloud/lib/public/Util.php","Line":323,"message":"OCP\\Util::numericToNumber(): Argument #1 ($number) must be of type string|int|float, null given, called in /var/www/nextcloud/lib/private/Files/Cache/Cache.php on line 162","exception":{},"CustomMessage":"OCP\\Util::numericToNumber(): Argument #1 ($number) must be of type string|int|float, null given, called in /var/www/nextcloud/lib/private/Files/Cache/Cache.php on line 162"}}
```

### Steps to reproduce
1. Spin up NC32 RC4
2. Install Groupfolders app 20.0.1
3. Enable App

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration

**PHP version:**
PHP docker container, based on Apache2 with PHP 8.2.29

**Database:**
MariaDB 10.6 via ProxySQL

**Nextcloud version:** (see Nextcloud admin page)
NC32 RC4

**Team folders version:**
v20.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from NC31 (migrated from ownCloud OC10 in the past)

**Where did you install Nextcloud from:**
https://download.nextcloud.com/server/prereleases/nextcloud-32.0.0rc4.zip

**Are you using external storage, if yes which one:** local/s3/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/Saml/...
OIDC (but normal login results in same behaviour)

### Client configuration
**Browser:**
Firefox

**Operating system:**
MacOS

### PR DESCRIPTION
**Pull request by come-nc**
Fix #4018 

The operator `<>` does not work for `NULL` values.

### CODE REVIEW

**Review by SystemKeeper — APPROVED** [review]

File: lib/Migration/Version20002Date20250612140256.php [hunk 1]
```diff
@@ -21,7 +21,7 @@
 /**
  * Adds root_id and options to the group folders table
  */
-class Version20001Date20250612140256 extends SimpleMigrationStep {
+class Version20002Date20250612140256 extends SimpleMigrationStep {
```
Comment (icewind1991) [inline lib/Migration/Version20002Date20250612140256.php]: Since this might have caused the issues like https://github.com/nextcloud/groupfolders/issues/4003, it's probably better to use https://github.com/nextcloud/groupfolders/pull/4022/ for this
